### ISSUE TITLE
BEUMC_... variable missing in BEM 

### ISSUE THREAD

**Issue by FrankBornais** [bcgov/SSGBM-VRI-BEM#19]
We could not find BEUMC_... attributes in the BEM we found in the BC data catalog.  

How should we create this information? 

https://github.com/bcgov/SSGBM-VRI-BEM/blob/a930c9dd9d3afd70aaaa08122b4e2e7ff52a22ca/Python_Scripts/01b_Step1_BEM_Corrections_BEC_Combo_Check_CSV_Output_v1.7.py#L131

**Comment by Jake-Bradshaw** [comment]
I have searched through files on our end and can't find where the BEUMC_... attributes are created. 

Karine has requested the BEI.shp file from the contractor - I am hoping that the BEUMC_... attributes are in that file, along with the TIES_ID. 

I will keep digging...

**Comment by FrankBornais** [comment]
BEUMC_... attributes were found in the contractor files. Closing this issue
