### ISSUE TITLE
Evelation Raster .gdb

### ISSUE THREAD

**Issue by FrankBornais** [bcgov/SSGBM-VRI-BEM#20]
.gbd Raster can only be read by ArcGis, no other application can read them or convert them, is it possible to have the raster in a compatible format with R?

**Comment by Jake-Bradshaw** [comment]
Sorry about that! I'll email the dem to you.

**Comment by Karine-Pigeon** [comment]
too large for email so just added the zipped tif to our shared dropbox folder

**Comment by meztez** [comment]
terra::rast
