### ISSUE TITLE
Merge of consolidated cutblocks and VRI

### ISSUE THREAD

**Issue by FrankBornais** [bcgov/SSGBM-VRI-BEM#21]
The merge for consolidated cutblocks and VRI is not in the script , it says it's in a separate script, can we have acces to this script as well?

**Comment by Jake-Bradshaw** [comment]
@Karine-Pigeon, the comment in script **4** below makes me think that this step was done manually in GIS. Appendix A in the report references (incorrectly) script **4a** when detailing how VRI age was updated with consolidated cutblock age. We do not have a **4a** and it seems like script **4**, which we do have, does that step. 

https://github.com/bcgov/SSGBM-VRI-BEM/blob/a930c9dd9d3afd70aaaa08122b4e2e7ff52a22ca/Python_Scripts/04_Add_LUT_age_classes_to_VRI_with_Consolidated_Cutblocks_VRIxBEM_2020.py#L19-L22

Appendix A in the report references:
**_CCL_** 
_Input_
Consolidated cutblock layer (CCL) was used to enhance the representation of recent harvesting in VRI (i.e., where VRI indicated a forest was old, but the CCL indicated it had been harvested the polygon age was updated to reflect the CCL data). 
_Script_
Script4a was run to incorporate any changes in age class data based on the projected age and consolidated cut block information. The CCL harvest date took precedence over the VRI harvest date.

**Comment by FrankBornais** [comment]
Handled in new function `merge_ccb_on_vri`
