### ISSUE TITLE
VRI sample does not contain PROJ_AGE_CLASS_CD_1

### ISSUE THREAD

**Issue by FrankBornais** [bcgov/SSGBM-VRI-BEM#22]
The script below makes some references to PROJ_AGE_CLASS_CD_1 and we do not have this information in the VRI sample.  Should we expect to find this information in another object or should we simply ignore this condition?  

It might be useless in the script since it only performs some validation that the object is structured properly but the information is not used later on.

https://github.com/bcgov/SSGBM-VRI-BEM/blob/a82157709ff4de6bb719fea189a7ed0e2c0e18f7/Python_Scripts/04_Add_LUT_age_classes_to_VRI_with_Consolidated_Cutblocks_VRIxBEM_2020.py#L61

**Comment by Jake-Bradshaw** [comment]
This was my mistake. I supplied you with the wrong file. I will ask Karine to upload the VRI data again.

**Comment by Karine-Pigeon** [comment]
Added VRI and BEM shapefiles to the shared dropbox folder (VRI_BEM) - The VRI shapefile should address both PROJ_AGE questions. Let us know if you prefer different format for spatial files. I think this is the easiest on our end.
